version: "3.5"
services:
  pxl_devbox:
    build: ./01_pxl_devbox
    image: "pxl_devbox:latest"
    container_name: "pxl_devbox"
    hostname: pxl_devbox
    restart: always
    ports:
      - "80:80"
      - "7777:7777"
    tty: true    
    networks:
      - pxl_influx_network
    volumes:
      - ./App:/home/user/app
      - ./Data:/home/user/data
      - ./Commands:/home/user/bin
      - ./Logs:/home/user/logs
      - ./Test:/home/user/test
      - /etc/localtime:/etc/localtime:ro
      
 # InfluxDB

  pxl_influxdb:
    restart: unless-stopped
    environment:
      - INFLUXDB_USER=${INFLUXDB_USER:-stage}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-stage}
      - GATEWAY_PORT=8086
    ports:
      - "8086:8086"
    healthcheck:
      test: "ln -sf /bin/busybox /bin/wget && /bin/wget -q -Y off http://pxl_influxdb:8086/metrics -O /dev/null > /dev/null 2>&1"
      interval: 25s
      timeout: 3s
      start_period: 30s
    build: ./02_influxdb
    image: "pxl_influxdb"
    container_name: "pxl_influxdb"
    hostname: "pxl_influxdb"
    networks:
      - pxl_influx_network
    volumes:
      - ./InfluxDB:/var/lib/influxdb  # Persist database data
      - ./InfluxMeta:/var/lib/influxdb/meta # Persist metadata
      - /etc/localtime:/etc/localtime:ro
      - ./Commands_Influx:/commands
  
  telegraf:
    image: telegraf:latest
    container_name: "telegraf"
    restart: unless-stopped
    depends_on:
      - pxl_influxdb
    volumes:
      - ./Telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/rootfs/proc:ro
      - /sys:/rootfs/sys:ro
      - /etc:/rootfs/etc:ro
    networks:
      - pxl_influx_network
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
      - INFLUX_BUCKET=$INFLUX_BUCKET
      - INFLUX_TOKEN=$INFLUX_TOKEN
      - INFLUX_ORG=$INFLUX_ORG
      
  

networks:
  pxl_influx_network:
    name: pxl_influx_network